title: <p align="center"> Vipul Singh </p>
logo: /assets/img/portfolio_pic.jpg

description: |
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/vipul-singh09/">LinkedIn</a> |
  <a href="https://github.com/bipulkumar1">GitHub</a>
  </p>
  <br>   
  I am working on Data Science, Big Data, Spark, Machine learning & NLP-related problems.
  Also handling Big Data from real-time Ad call data.
  Worked with IBM Research in the Big Data Analytics team.
  Working in the AdTech domain for 3 years.
  <br>

subtitle:
  certifications:
    - "Data Science (pdf/data_science.pdf)"
    - "Machine Learning (pdf/machine_learning.pdf)"
    - "Deep Learning (pdf/deep_learning.pdf)"

  education:
    - "Bachelor of Technology in Computer Science - XYZ University"
    - "Master's in Data Science - ABC University"

  experience:
    - "Software Engineer at Company A (2020-2022)"
    - "Data Scientist at Company B (2022-Present)"

theme: jekyll-theme-mini
