title: <p align="center"> Vipul Singh </p>


description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="www.linkedin.com/in/vipul-singh09"LinkedIn</a> |
  <a href="https://github.com/bipulkumar1">GitHub</a>
  </p>



theme: jekyll-theme-minimal
footer: false 
